name: Reusable Build & Push Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Image name'
        required: true
        type: string
      dockerfile-path:
        description: 'Dockerfile path'
        required: false
        default: './Dockerfile'
        type: string
      context:
        description: 'Context path'
        required: false
        default: '.'
        type: string
      registry:
        description: 'Container Registry'
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        description: 'Username'
        required: true
      REGISTRY_PASSWORD:
        description: 'Token'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3

      - name: Login Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate Tags
        id: gen_tags
        run: |
          DATE_TAG=$(date -u +"%Y%m%d%H%M%S")
          echo "date_tag=${DATE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image-name }}:${{ steps.gen_tags.outputs.date_tag }}
            ${{ inputs.registry }}/${{ inputs.image-name }}:latest
